name: Daily tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-ut:
    uses: ./.github/workflows/build-and-ut.yml
  code-analysis:
    uses: ./.github/workflows/code-analysis.yml
